apiVersion: v2
name: kubernetes-event-exporter
description: A Helm chart for Kubernetes Event Exporter
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/blaxel-ai/kubernetes-event-exporter
sources:
  - https://github.com/blaxel-ai/kubernetes-event-exporter
maintainers:
  - name: Blaxel AI
    email: support@blaxel.ai
keywords:
  - kubernetes
  - events
  - monitoring
  - eventbridge
  - exporter 