{{- if not .Values.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: {{ .Values.config.logLevel }}
    logFormat: {{ .Values.config.logFormat }}
    {{- if .Values.config.maxEventAgeSeconds }}
    maxEventAgeSeconds: {{ .Values.config.maxEventAgeSeconds }}
    {{- end }}
    {{- if .Values.config.kubeQPS }}
    kubeQPS: {{ .Values.config.kubeQPS }}
    {{- end }}
    {{- if .Values.config.kubeBurst }}
    kubeBurst: {{ .Values.config.kubeBurst }}
    {{- end }}
    {{- if .Values.config.metricsNamePrefix }}
    metricsNamePrefix: {{ .Values.config.metricsNamePrefix }}
    {{- end }}
    
    route:
      routes:
        {{- range .Values.routes }}
        - match:
            {{- range .match }}
            - receiver: {{ .receiver | quote }}
            {{- end }}
        {{- end }}
    
    receivers:
      {{- if .Values.receivers.eventbridge.enabled }}
      - name: "eventbridge"
        eventbridge:
          region: {{ .Values.aws.region | quote }}
          eventBusName: {{ .Values.eventbridge.eventBusName | quote }}
          detailType: {{ .Values.eventbridge.detailType | quote }}
          source: {{ .Values.eventbridge.source | quote }}
          detail:
            specversion: "1.0"
            type: "ai.blaxel.executionplane.kubernetes.{{ "{{ .Type | lower }}" }}"
            source: "/executionplane/{{ "{{ .ClusterName | default \\\"${CLUSTER_NAME}\\\" | default \\\"unknown\\\" }}" }}/{{ "{{ .Namespace }}" }}"
            id: "{{ "{{ .UID }}" }}"
            time: "{{ "{{ .LastTimestamp }}" }}"
            datacontenttype: "application/json"
            subject: "{{ "{{ .InvolvedObject.Kind }}" }}/{{ "{{ .InvolvedObject.Namespace }}" }}/{{ "{{ .InvolvedObject.Name }}" }}"
            cluster: "{{ "{{ .ClusterName | default \\\"${CLUSTER_NAME}\\\" | default \\\"unknown\\\" }}" }}"
            region: {{ .Values.aws.region | quote }}
            data:
              message: "{{ "{{ .Message }}" }}"
              reason: "{{ "{{ .Reason }}" }}"
              type: "{{ "{{ .Type }}" }}"
              namespace: "{{ "{{ .Namespace }}" }}"
              cluster: "{{ "{{ .ClusterName | default \\\"${CLUSTER_NAME}\\\" | default \\\"unknown\\\" }}" }}"
              involvedObject:
                kind: "{{ "{{ .InvolvedObject.Kind }}" }}"
                name: "{{ "{{ .InvolvedObject.Name }}" }}"
                namespace: "{{ "{{ .InvolvedObject.Namespace }}" }}"
                apiVersion: "{{ "{{ .InvolvedObject.APIVersion }}" }}"
                uid: "{{ "{{ .InvolvedObject.UID }}" }}"
              source:
                component: "{{ "{{ .Source.Component }}" }}"
                host: "{{ "{{ .Source.Host }}" }}"
              firstTimestamp: "{{ "{{ .FirstTimestamp }}" }}"
              lastTimestamp: "{{ "{{ .LastTimestamp }}" }}"
              count: "{{ "{{ .Count }}" }}"
              reportingController: "{{ "{{ .ReportingController }}" }}"
              reportingInstance: "{{ "{{ .ReportingInstance }}" }}"
      {{- end }}
      
      {{- if .Values.receivers.stdout.enabled }}
      - name: "stdout"
        stdout:
          {{- if .Values.receivers.stdout.deDot }}
          deDot: {{ .Values.receivers.stdout.deDot }}
          {{- end }}
      {{- end }}
{{- end }} 