{{- if and .Values.aws.enabled (not .Values.aws.existingSecret) .Values.aws.credentials.accessKeyId -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-aws
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.credentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.credentials.secretAccessKey | quote }}
  {{- if .Values.aws.credentials.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.aws.credentials.sessionToken | quote }}
  {{- end }}
{{- end }} 