logLevel: debug
logFormat: json
maxEventAgeSeconds: 60
kubeQPS: 100
kubeBurst: 500

route:
  routes:
    # Route all events to EventBridge
    - match:
        - receiver: "eventbridge"
    
    # Route critical events (non-Normal) to EventBridge with different detail type
    - match:
        - receiver: "eventbridge-critical"
      drop:
        - type: "Normal"
    
    # Also log all events to stdout for debugging
    - match:
        - receiver: "stdout"

receivers:
  - name: "eventbridge"
    eventbridge:
      detailType: "kubernetes-event"
      source: "kubernetes.local"
      eventBusName: "default"
      region: "us-east-1"  # Change this to your AWS region
      details:
        message: "{{ .Message }}"
        namespace: "{{ .Namespace }}"
        reason: "{{ .Reason }}"
        type: "{{ .Type }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
        component: "{{ .Source.Component }}"
        host: "{{ .Source.Host }}"
        firstTimestamp: "{{ .FirstTimestamp }}"
        lastTimestamp: "{{ .LastTimestamp }}"
        count: "{{ .Count }}"
        eventTime: "{{ .EventTime }}"
  
  - name: "eventbridge-critical"
    eventbridge:
      detailType: "kubernetes-critical-event"
      source: "kubernetes.local"
      eventBusName: "default"
      region: "us-east-1"  # Change this to your AWS region
      details:
        message: "{{ .Message }}"
        namespace: "{{ .Namespace }}"
        reason: "{{ .Reason }}"
        type: "{{ .Type }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
        component: "{{ .Source.Component }}"
        host: "{{ .Source.Host }}"
        firstTimestamp: "{{ .FirstTimestamp }}"
        lastTimestamp: "{{ .LastTimestamp }}"
        count: "{{ .Count }}"
        eventTime: "{{ .EventTime }}"
        labels: "{{ toJson .InvolvedObject.Labels}}"
  
  - name: "stdout"
    stdout:
      deDot: true 