# Example: Creating an AWS credentials secret
# 
# NOTE: This is typically NOT needed when running on EKS!
# On EKS, use IAM Roles for Service Accounts (IRSA) instead.
# See values-eks-irsa.yaml for the recommended approach.
#
# Only use this for:
# - Non-EKS clusters
# - Local development/testing
# - Specific scenarios where IRSA cannot be used
#
# kubectl apply -f aws-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  AWS_SESSION_TOKEN: "optional-session-token"  # Optional, remove if not using temporary credentials 