# Example values file using an existing AWS secret
# helm install event-exporter ./helm/kubernetes-event-exporter -f examples/values-with-existing-secret.yaml

cluster:
  name: "my-production-cluster"

aws:
  enabled: true
  region: "us-east-1"
  # Reference the existing secret created from aws-secret.yaml
  existingSecret: "aws-credentials"
  secretKeys:
    accessKeyId: "AWS_ACCESS_KEY_ID"
    secretAccessKey: "AWS_SECRET_ACCESS_KEY"
    sessionToken: "AWS_SESSION_TOKEN"

eventbridge:
  enabled: true
  eventBusName: "default"
  detailType: "Kubernetes Event"
  source: "kubernetes.production"

# Only send Warning and Error events to EventBridge
routes:
  - match:
      - receiver: "eventbridge"
  - match:
      - receiver: "stdout"

receivers:
  eventbridge:
    enabled: true
  stdout:
    enabled: false  # Disable stdout in production 